package com.example.administrator.opencvdemo.util;

/**
 * @author 吴祖清
 * @version $Rev$
 * @createTime 2017/12/22 14:37
 * @des ${TODO}
 * @updateAuthor $Author$
 * @updateDate 2017/12/22$
 * @updateDes ${TODO}
 */

public interface Constant {


    String KEY_LAO_FANG = "KEY_LAO_FANG";
    String KEY_MO_BAI_KUA_FU = "KEY_MO_BAI_KUA_FU";
    String KEY_ZHAO_HUAN = "KEY_ZHAO_HUAN";
    String KEY_YAN_HUI_NUMBER = "KEY_YAN_HUI_NUMBER";
    String KEY_WORK_ZW = "KEY_WORK_ZW";
    String KEY_LOOP = "KEY_LOOP";
    String KEY_WORK_FL = "KEY_WORK_FL";
    String KEY_WORK_ONLY_FL = "KEY_WORK_ONLY_FL";
    String KEY_WORK_MB = "KEY_WORK_MB";
    String KEY_WORK_KF_MB = "KEY_WORK_KF_MB";
    String KEY_WORK_TASK = "KEY_WORK_TASK";
    String KEY_CHOU_CAI = "KEY_CHOU_CAI";
    String KEY_GUAN_KA = "KEY_GUAN_KA";
    String KEY_SHU_YUAN = "KEY_SHU_YUAN";
    String KEY_YAN_HUI = "KEY_YAN_HUI";
    String KEY_REGISTER = "KEY_REGISTER";
    String KEY_XIAN_SHI = "KEY_XIAN_SHI";
    String KEY_CHENG_JIU = "KEY_CHENG_JIU";
    String KEY_EMAIL = "KEY_EMAIL";
    String KEY_OLD_SHOU_CAI = "KEY_OLD_SHOU_CAI";
    String KEY_LIAN_MENG = "KEY_LIAN_MENG";
    String KEY_GUAN_YAN = "KEY_GUAN_YAN";
    String KEY_GENG_XIN = "KEY_GENG_XIN";
    String KEY_LIAN_MENG_FU_BEN = "KEY_LIAN_MENG_FU_BEN";
    String KEY_KUA_FU_JL = "KEY_KUA_FU_JL";
    String KEY_YA_MEN = "KEY_YA_MEN";
    String KEY_XB_BUY = "KEY_XB_BUY";
    String KEY_XB_USE = "KEY_XB_USE";

    String KEY_SPACE_TIME_TWO = "KEY_SPACE_TIME_TWO";
    String KEY_SPACE_TIME_FOUR = "KEY_SPACE_TIME_FOUR";
    String KEY_SPACE_TIME_THREE = "KEY_SPACE_TIME_THREE";
    String KEY_SPACE_TIME_SHU_YUAN = "KEY_SPACE_TIME_SHU_YUAN";
    String KEY_SPACE_TIME_ONE = "KEY_SPACE_TIME_ONE";


    String COORDINATE_KEY = "COORDINATE_KEY";


    String SCREEN_CLOSE = "SCREEN_CLOSE";
    String CHU_FU = "CHU_FU";

    String NET_CLOSE = "NET_CLOSE";
    String JYZC_SY = "JYZC_SY";//商产
    String JYZC_NY = "JYZC_NY";//农产
    String JYZC_SB = "JYZC_SB";    //士兵
    String JYZC_ZS = "JYZC_ZS";    //征收


    String UPGRADE = "UPGRADE";    //升级
    String LOGIN_GAME = "LOGIN_GAME"; //登陆游戏
    String START_GAME = "START_GAME"; //进入游戏
    String GAME_NOTICE_DIALOG_CLOSE = "GAME_NOTICE_DIALOG_CLOSE";
    String GEN_XIN = "GEN_XIN";
    String HUA_AN = "HUA_AN";


    String CLZW_BG = "CLZW_BG";               //政绩
    String CLZW_GET = "CLZW_GET";               //政绩
    String SHI_YE = "SHI_YE";                   //师爷

    String HUANG_GONG = "HUANG_GONG";       //皇宫
    String HUANG_GONG_CLOSE = "HUANG_GONG_CLOSE";       //皇宫
    String HUANG_GONG_WANG = "HUANG_GONG_WANG";       //皇宫
    String HUANG_GONG_GET = "HUANG_GONG_GET";//领取俸禄

    String PAI_HANG_BANG = "PAI_HANG_BANG";//排行
    String BANG_DAN_SELF = "BANG_DAN_SELF"; //本服榜单
    String BANG_DAN_CROSS = "BANG_DAN_CROSS";//跨服榜单
    String BANG_DAN_GUAN_KA = "BANG_DAN_GUAN_KA";//跨服关卡
    String BANG_DAN_QIN_MI = "BANG_DAN_QIN_MI";//跨服亲密
    String BANG_DAN_GET = "BANG_DAN_GET";//膜拜
    String BANG_DAN_KF_GET = "BANG_DAN_KF_GET";//膜拜


    String TAB_TASK = "TAB_TASK";//任务

    String TASK_TOP_10 = "TASK_TOP_10";
    String TASK_TOP_30 = "TASK_TOP_30";
    String TASK_TOP_60 = "TASK_TOP_60";
    String TASK_TOP_100 = "TASK_TOP_100";
    String TASK_TOP_140 = "TASK_TOP_140";

    String TASK_RIGHT_1 = "TASK_RIGHT_1";
    String TASK_RIGHT_2 = "TASK_RIGHT_2";
    String TASK_RIGHT_3=  "TASK_RIGHT_3";
    String TASK_RIGHT_4 = "TASK_RIGHT_4";
    String TASK_RIGHT_5 = "TASK_RIGHT_5";


    String TASK_DIALOG_CLOSE = "TASK_DIALOG_CLOSE";
    String TASK_DIALOG_CLOSE_140 = "TASK_DIALOG_CLOSE_140";

    String TASK_RIGHT_START_GET = "TASK_RIGHT_START_GET";  //福利
    String TASK_RIGHT_END_GET = "TASK_RIGHT_END_GET";       //福利领取


    String ACADEMY = "ACADEMY";//书院


    String ACADEMY_GET_1 = "ACADEMY_GET_1";//书院背景
    String ACADEMY_GET_2 = "ACADEMY_GET_2";//书院背景
    String ACADEMY_GET_3 = "ACADEMY_GET_3";//书院背景
    String ACADEMY_GET_4 = "ACADEMY_GET_4";//书院背景

    String ACADEMY_GET_OK = "ACADEMY_GET_OK";//书院门客确定
    String ACADEMY_ONE_KEY = "ACADEMY_ONE_KEY";//一件完成

    String GUAN_KA = "GUAN_KA";

    String GUAN_KA_DIALOG_CLOSE = "GUAN_KA_DIALOG_CLOSE";
    String GUAN_KA_START_ZHUAN_DOU = "GUAN_KA_START_ZHUAN_DOU";
    String GUAN_KA_START_ZHUAN_DOU_BG = "GUAN_KA_START_ZHUAN_DOU_BG";
    String GUAN_KA_XX_START = "GUAN_KA_XX_START";
    String GUAN_KA_XX_END = "GUAN_KA_XX_END";
    String GUAN_KA_BOSS = "GUAN_KA_BOSS";
    String GUAN_KA_VICTORY = "GUAN_KA_VICTORY";
    String GUAN_KA_POSITION_CLOSE = "GUAN_KA_POSITION_CLOSE";
    String GUAN_KA_BLOOD_VOLUME = "GUAN_KA_BLOOD_VOLUME";
    String GUAN_KA_POSITION_PLOT = "GUAN_KA_POSITION_PLOT";
    String GUAN_KA_POSITION_PLOT2 = "GUAN_KA_POSITION_PLOT2";

    String YAN_HUI_CLICK = "YAN_HUI_CLICK";
    String YAN_HUI_NUMBER = "YAN_HUI_NUMBER";
    String YAN_HUI_INPUT = "YAN_HUI_INPUT";
    String YAN_HUI_SEARCH = "YAN_HUI_SEARCH";
    String YAN_HUI_GO = "YAN_HUI_GO";
    String YAN_HUI_GAO_JI = "YAN_HUI_GAO_JI";
    String YAN_HUI_POSITION_START = "YAN_HUI_POSITION_START";
    String YAN_HUI_POSITION_END = "YAN_HUI_POSITION_END";
    String YAN_HUI_POSITION_LEFT = "YAN_HUI_POSITION_LEFT";
    String YAN_HUI_POSITION_RIGHT = "YAN_HUI_POSITION_RIGHT";
    String YAN_HUI_OK = "YAN_HUI_OK";
    String YAN_HUI_DIALOG_CLOSE = "YAN_HUI_DIALOG_CLOSE";



    String CHENG_JIU_CLICK = "CHENG_JIU_CLICK";
    String CHENG_JIU_RED_POINT = "CHENG_JIU_RED_POINT";
    String CHENG_JIU_LEFT = "CHENG_JIU_LEFT";
    String CHENG_JIU_RIGHT = "CHENG_JIU_RIGHT";
    String CHENG_JIU_CLOSE = "CHENG_JIU_CLOSE";
    String CHENG_JIU_GET_1 = "CHENG_JIU_GET_1";
    String CHENG_JIU_GET_2 = "CHENG_JIU_GET_2";
    String CHENG_JIU_GET_3 = "CHENG_JIU_GET_3";
    String CHENG_JIU_GET_4 = "CHENG_JIU_GET_4";
    String CHENG_JIU_GET_5 = "CHENG_JIU_GET_5";

    String CURRENT_TASK_STEP  = "CURRENT_TASK_STEP";
    String CURRENT_PAGE  = "CURRENT_PAGE";
    String REGISTER_CLICK  = "REGISTER_CLICK";
    String REALY_NAME_OK = "REALY_NAME_OK";
    String REGISTER_OK = "REGISTER_OK";
    String CREATE_USER = "CREATE_USER";
    String REGISTER_OTHER = "REGISTER_OTHER";

    String TIME_LIMIT_REWARD1 = "TIME_LIMIT_REWARD1";
    String TIME_LIMIT_REWARD1_GET_1 = "TIME_LIMIT_REWARD1_GET_1";
    String TIME_LIMIT_REWARD1_GET_2 = "TIME_LIMIT_REWARD1_GET_2";
    String TIME_LIMIT_REWARD1_GET_3 = "TIME_LIMIT_REWARD1_GET_3";
    String TIME_LIMIT_REWARD1_CLOSE = "TIME_LIMIT_REWARD1_CLOSE";
    String EMAIL_RED = "EMAIL_RED";
    String EMAIL_DIALOG_CLOSE = "EMAIL_DIALOG_CLOSE";
    String EMAIL_OK = "EMAIL_OK";
    String EMAIL_1 = "EMAIL_1";
    String EMAIL_2 = "EMAIL_2";
    String EMAIL_3 = "EMAIL_3";
    String EMAIL_4 = "EMAIL_4";
    String EMAIL_5 = "EMAIL_5";

    String SHI_JI_ZHAO_HUAN = "SHI_JI_ZHAO_HUAN";
    String SHI_JI_ZHAO_HUAN_OK = "SHI_JI_ZHAO_HUAN_OK";
    String SHI_JI_ZHAO_HUAN_ZI_SI = "SHI_JI_ZHAO_HUAN_ZI_SI";
    String SHI_JI_ONE_KEY_ZH = "SHI_JI_ONE_KEY_ZH";


    String LIAN_MENG = "LIAN_MENG";
    String LIAN_MENG_CHA_XUN = "LIAN_MENG_CHA_XUN";
    String LIAN_MENG_SEARCH_INPUT = "LIAN_MENG_SEARCH_INPUT";
    String LIAN_MENG_SEARCH_SEARCH = "LIAN_MENG_SEARCH_SEARCH";
    String LIAN_MENG_JOIN = "LIAN_MENG_JOIN";

    String LIAN_MENG_MANAGER = "LIAN_MENG_MANAGER";
    String LIAN_MENG_MEI_RI_JIAN_SHE = "LIAN_MENG_MEI_RI_JIAN_SHE";
    String LIAN_MENG_MEI_RI_JIAN_SHE_GAO_JI = "LIAN_MENG_MEI_RI_JIAN_SHE_GAO_JI";
    String LIAN_MENG_MEI_RI_JIAN_SHE_CLOSE = "LIAN_MENG_MEI_RI_JIAN_SHE_CLOSE";
    String LIAN_MENG_MEMBER = "LIAN_MENG_MEMBER";
    String LIAN_MENG_MEMBER_EXIT = "LIAN_MENG_MEMBER_EXIT";
    String LIAN_MENG_MEMBER_EXIT_OK = "LIAN_MENG_MEMBER_EXIT_OK";

    String LIAN_MENG_FU_BEN = "LIAN_MENG_FU_BEN";
    String LIAN_MENG_GONG_XIAN = "LIAN_MENG_GONG_XIAN";
    String LIAN_MENG_DUI_HUAN = "LIAN_MENG_DUI_HUAN";
    String LIAN_MENG_FU_BEN_KILL = "LIAN_MENG_FU_BEN_KILL";
    String LIAN_MENG_FU_BEN_CLOSE = "LIAN_MENG_FU_BEN_CLOSE";

    String KUA_FU_LJ_JOIN = "KUA_FU_LJ_JOIN";
    String KUA_FU_LJ_GET = "KUA_FU_LJ_GET";


    String ZHENG_JIU_POINT = "ZHENG_JIU_POINT";
    String LAO_FANG_MAP = "LAO_FANG_MAP";
    String LAO_FANG_PEOPLE = "LAO_FANG_PEOPLE";

    String YA_MEN_MAP = "YA_MEN_MAP";
    String YA_MEN_INDEX = "YA_MEN_INDEX";
    String YA_MEN_ZHUN_ZOU = "YA_MEN_ZHUN_ZOU";
    String YA_MEN_PK_VS = "YA_MEN_PK_VS";
    String YA_MEN_PK_UN_BUY = "YA_MEN_PK_UN_BUY";
    String YA_MEN_TEMP_DIALOG_HIDE = "YA_MEN_TEMP_DIALOG_HIDE";
    // String YA_MEN_CHOOSE_YING_LIAN_SHENG = "YA_MEN_CHOOSE_YING_LIAN_SHENG";
    // String YA_MEN_CHOOSE_YING_LIAN_SHENG_ONE = "YA_MEN_CHOOSE_YING_LIAN_SHENG_ONE";
    String YA_MEN_CHOOSE_SKIP = "YA_MEN_CHOOSE_SKIP";
    String YA_MEN_LIAN_SHENG = "YA_MEN_LIAN_SHENG";
    String YA_MEN_TEMP_DIALOG_CLOSE = "YA_MEN_TEMP_DIALOG_CLOSE";
    String YA_MEN_END = "YA_MEN_END";
    String YA_MEN_WAIT = "YA_MEN_WAIT";

    /**
     * 底部按钮
     */
    String BOTTOM_MK = "BOTTOM_MK";
    String BOTTOM_DJ = "BOTTOM_DJ";
    String BOTTOM_RW = "BOTTOM_RW";
    String BOTTOM_CJ = "BOTTOM_CJ";
    String BOTTOM_SC = "BOTTOM_SC";
    String BOTTOM_FL = "BOTTOM_FL";
    String GUO_JIA = "GUO_JIA";

    String SHUYUAN_GET_1 = "SHUYUAN_GET_1";//书院背景
    String SHUYUAN_GET_2 = "SHUYUAN_GET_2";//书院背景
    String SHUYUAN_GET_3 = "SHUYUAN_GET_3";//书院背景
    String SHUYUAN_GET_4 = "SHUYUAN_GET_4";//书院背景
    String SHUYUAN_GET_5 = "SHUYUAN_GET_5";//书院背景
    String SHUYUAN_GET_6 = "SHUYUAN_GET_6";//书院背景

    int RESET_TASK = 200;
    int TASK_ERROR = 100;
    int TASK_TOAST = 500;
    int TASK_STOP = 2500;
    int TASK_TOAST_COUNT_DOWN = 1500;
    int SCREEN_OFF = 999;
    int SHOW_ORC_PAGE = 300;
//     int SCREEN_ON = 992;


    String HUO_DONG_SHANG_PU = "HUO_DONG_SHANG_PU";
    String HUO_DONG_LI_BAO_1 = "HUO_DONG_LI_BAO_1";
    String HUO_DONG_LI_BAO_2 = "HUO_DONG_LI_BAO_2";
    String HUO_DONG_JIN_RU = "HUO_DONG_JIN_RU";
    String HUO_DONG_PROP = "HUO_DONG_PROP";
    String HUO_DONG_SHI_YONG = "HUO_DONG_SHI_YONG";


    interface Login{
        String TY_OVER = "TY_OVER";//是否激活码到期
        String IS_TY = "IS_TY"; //是否是体验
    }
}
